import React from 'react';

export default function ReportHeader() {
  return (
    <div className="border-b-2 border-slate-800 pb-6 mb-8 text-center print:mb-6">
      <h1 className="text-2xl md:text-3xl font-bold uppercase tracking-wide text-slate-900 mb-2">
        Official Test Report
      </h1>
      <h2 className="text-lg md:text-xl font-medium text-slate-700">
        Non-Automatic Weighing Instrument (NAWI)
      </h2>
      <p className="text-sm text-slate-500 mt-2">
        Generated by Legal Metrology Inspection System
      </p>
    </div>
  );
}

